### ISSUE TITLE
New feature: Block

### ISSUE THREAD

**Issue by bashbashbash** [SIGBlockchain/project_aurum#10]
**Workspace:**
- producer/src/block/block.go
- producer/src/block/block_test.go

**Objective:**
Blocks are the element types that make up the blockchain. The blockchain is essentially a chronologically ordered hash-linked list that contains bundled data.

So we need a block `struct`. This contains several important pieces of metadata about the block. 
- The first thing is the version number. With future development, our project may have updates that change the way the system behaves. In this case, we mark down what version we're using. This is important because this way we can identify blocks that may be subject to different rules that might not be compatible with older versions. 
- The height of the block is the index of the block in the blockchain. 
- The previous hash is the hash of the previous block, which acts sort of like a pointer in a linked-list. 
- The Merkle root hash is a way to compress a slice of data into a single hash. 
- The timestamp is necessary to show chronological ordering. It should be the timestamp of the moment the block is generated.
- Everything above represents the **block header**, which is the metadata of the block. So the actual data is the **block body.** In this case we're going to use transactions as data, which aren't implemented yet. So to be clear, a **block** is made up of a **block header** and a **block body**.

**Testing:**
Test cases that must be passed:

1. (COMPLETED) Create a `block.go` file and a `block_test.go` file in the `producer/src` directory.
2. (COMPLETED) Create a struct called Block with the following fields:
- `Version` - integer
- `Height` - integer
- `PreviousHash` - byte slice
- `MerkleRootHash` - byte slice
- `Timestamp` - integer
------------------------------- everything above this line is the **block header**, below is the **block body**.
- `Data` - a slice of byte slices (`[][]byte`)
3. Create a receiver function for the `Block` struct called `Serialize`. This should cast all non-byte slice fields of the **block header** struct to byte slices. Then, concatenate all the fields of the **block header** together in order. Then finally, concatenate each element of the **block body** to the **block header**. This should result in one long byte slice.

**EDIT**: When concatenating the **block body** to the **block header**, first append the number of `slices` in the `data slice` as an integer in byte form. 

Before concatenating an element of `data`, prepend its `len` in byte form to that element.

**Resources:**
- [Go SHA-256 Package](https://golang.org/pkg/crypto/sha256/)
- [Go Time Package](https://golang.org/pkg/time/)
- [Go Testing Package](https://golang.org/pkg/testing/)
- [Go Logging Package](https://golang.org/pkg/log/) (for detailed debug printing)

**Comment by kstola2** [comment]
It may be a good idea to incorporate a `Serializable` interface for the `HashSHA256` function to take in.

**Comment by kstola2** [comment]
Completed
