### ISSUE TITLE
Fixing Relative Import Paths

### ISSUE THREAD

**Issue by jldistefano** [SIGBlockchain/project_aurum#105]
**Workspace:**
Pretty much all source code files

**Objective:**
This has been a problem for a while, but much of our code depends on relative paths, meaning that it depends on where the code is being executed. This is in fact *no bueno* as the code could be executed anywhere and Golang is **REALLY** finicky about paths. So we should change the relative import paths to depend on the GOPATH variable instead.

**Directive:**
We need to now assume that our project will be installed in a similar directory to other github packages. So the new directory would be `go/src/github.com/SIGBlockchain/project_aurum/...`. All import paths should now be based off the GOPATH, see resources on how to access that inside of code.

**Testing:**
All other tests should work properly

**Resources:**
[Import Paths](https://scene-si.org/2018/01/25/go-tips-and-tricks-almost-everything-about-imports/)
[Relative Import Paths](https://stackoverflow.com/questions/38517593/relative-imports-in-go)

**Comment by kstola2** [comment]
Completed
