### ISSUE TITLE
Claims for Contracts 

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#109]
**Expected Date of Completion:** 17-March-2019

**Workspace:**
- `producer/src/contract/contract.go`
- `producer/src/contract/contract_test.go`

**Objective:**
Review the way contracts work by reading through the [slides on them](https://github.com/SIGBlockchain/project_aurum/blob/dev/docs/Contracts.pdf).

Claims consume or "claim" unclaimed yields. Our yields live inside the UYP (unclaimed yield pool). When a claim is made, it removes a valid yield from that pool and stores some metadata about the yield. 

A Claim must have:
- The contract hash of the contract that the yield being claimed is stored in
- The index of the block that contract is stored in
- The index of the yield being claimed in the array of yields of that contract
- The claimant's public key
- The signature of the claimant (**DO NOT WORRY ABOUT THE SIGNATURE FOR THIS ISSUE - IT IS NOT BEING TESTED**)

You will need to create custom error structs for this issue. In the resources section you will find a quick tutorial on how to use them.

 The UYP has 4 fields:
- The height of the block that the contract which has the yield is stored in.
- The hash of the contract the yield is stored in
- The index of the yield in the array of yields in that contract
- The rightful holder of the aurum in that yield (ie. the only authorized claimant)
- The value of that yield

Big picture representation:
![image](https://user-images.githubusercontent.com/31855040/54449598-7dfe8780-471c-11e9-9369-c7ad9444c5f6.png)

**Testing:**
Tests are located in `contract_test.go`.

**Resources:**
- [Go errors](https://gobyexample.com/errors)
- [Go ecdsa](https://golang.org/pkg/crypto/ecdsa/)
- [Contracts](https://github.com/SIGBlockchain/project_aurum/blob/dev/docs/Contracts.pdf)

**Comment by Vineet77** [comment]
If anyone wants to work along with me, let me know!

**Comment by kstola2** [comment]
Going to close this for now while we try using the account based system. If it doesn't work, we will reopen.
