### ISSUE TITLE
Client: Online Status

### ISSUE THREAD

**Issue by jldistefano** [SIGBlockchain/project_aurum#11]
**NOTE:** This requires issue #9 to be complete.

**Workspace:**
- client/src/client/client.go
- client/src/client/client_test.go
- client/src/main/main.go

**Objective:**
In order for the user to be able to use the program, the user must be online. 

**Testing:**
1. There's a function in `producer.go` called `CheckConnectivity`. You can use this function whether the client is online or not. You can either create this function again in `client.go` and test it the same way in `client_test.go`. Regardless, in the client's `main.go`, `CheckConnectivity` should be called. If it returns an `err` not equal to `nil`, it should log the problem and exit the program. Otherwise it should just return gracefully. This is pretty much literally the same thing as the first few lines of `main.go` in `producer/`.

**Resources:**
- [Go Testing Package](https://golang.org/pkg/testing/)
- [Go Net Package](https://golang.org/pkg/net/)
- [Go Logging Package](https://golang.org/pkg/log/) (for detailed debug printing)

**Comment by kstola2** [comment]
Completed.
