### ISSUE TITLE
Recover Metadata feature

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#132]
**IMPORTANT:**
There is a branch called `recover-metadata`. Make a branch based off of this branch to work on. Please do **not** push to this branch directly.

**Workspace:**
- `producer blockchain package`

**Objective:**
This is a security feature for the ledger. If the block table gets lost somehow, this function will restore it completely. Another situation is when a producer in a decentralzied system joins the network and wants the full ledger.

Function stub and unit test are located in the `blockchain` package. Please refrain from changing the unit test.

**Comment by HarryL5004** [comment]
Hi, I'm able to pass the unit test if I make the following changes to the it.

![issues](https://user-images.githubusercontent.com/42977312/55270927-295a2100-5273-11e9-9cb9-f7d7b7c3ed45.png)

Should I proceed to make these changes?

**Comment by kstola2** [comment]
Yeah that should be fine. Are they not initially passing because of `undefined` errors?

**Comment by HarryL5004** [comment]
Yep, the test file could not compile because of undefined errors

**Comment by kstola2** [comment]
That's my bad then, go ahead and make those changes. Feel free to make a PR to `dev` when you're ready.

**Comment by HarryL5004** [comment]
I have one more question. In my RecoverBlockchainMetadata function, I created a file called "Database.db" if the database doesn't exist. And when I run the unit test, it creates two additional files, one called "Database.db" and the other called "testDatabase.db". However, this doesn't occur if I change the name "Database.db" to "testDatabase.db" in my RecoverBlockchainMetadata function. Running the unit test will only create a file called "testDatabase.db". So I'm wondering if I should just leave it as it is.

![image](https://user-images.githubusercontent.com/42977312/55271204-16495000-5277-11e9-89d8-afdf50e2c8ff.png)

![image](https://user-images.githubusercontent.com/42977312/55271284-3d545180-5278-11e9-968e-be8deab6d3fe.png)

**Comment by kstola2** [comment]
Hmm. I think I know what you mean. Make your PR and I'll check it out. We can discuss changes there.

**Comment by kstola2** [comment]
@HarryL5004 please comment "completed" before closing an issue.

**Comment by HarryL5004** [comment]
Completed
