### ISSUE TITLE
Version block field convert to uint16

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#134]
I believe that it may be best to crunch down the `Version` field in the `Block` struct to a 16 bit number instead of a 32 bit. The reason for this is two-fold: I doubt we will have 4-billion+ versions, and this saves a little bit of storage space on each block made. 

Changing the `Version` will probably make a lot of tests fail all over the project, so this fix will be widespread.

**Comment by jldistefano** [comment]
Completed
