### ISSUE TITLE
docker-compose file for Producer

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#135]
Building on issue #119 , we need to build our `docker-compose.yml` file in order to fully automate our containerization. Using [allium's compose file](https://github.com/SIGBlockchain/project_allium/blob/p2p_priv/docker-compose.yml) as a reference, spin up a docker container with a `producer`, and have it connect to a network called `aurum-net`. Note this cannot be completed unless #119 is completed. 

Some resources on `docker-compose`:

https://docs.docker.com/compose/compose-file/
https://blog.codeship.com/orchestrate-containers-for-development-with-docker-compose/
https://takacsmark.com/docker-compose-tutorial-beginners-by-example-basics/

**Comment by Vineet77** [comment]
I'm putting the compose fill right under the main directory, as I suppose we may have a client program along with a client docker file

**Comment by Vineet77** [comment]
What's the point of having allium-net? Docker by default creates a single network accessible by all containers

**Comment by kstola2** [comment]
Iirc that default network is named something pseudorandomly each startup, so creating your own own creates a static named network for your nodes to connect to.

**Comment by kstola2** [comment]
completed
