### ISSUE TITLE
root test package with GenerateNRandomKeys feature

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#145]
**IMPORTANT:**
There is a branch called `test-package`. Make a branch based off of this branch to work on. Please do **not** push to this branch directly.

**Expected Date of Completion:** 21-April-2019

**Workspace:**
- test package (at root)

**Objective:**
This package is exclusive for testing. It will be used for our Dockerfile to run some tests simulating network behavior after an airdrop. The `accounts` package isn't quite done yet as of writing this issue, so for now the only function that can be implemented is the `GenerateNRandomKeys` funciton. Don't worry about the `main` package inside of `test`, just implement the aforementioned function to pass the test.

The `test` package in the `producer-accounts` branch has function stubs and unit tests. Please refrain from changing the unit tests. If it is absolutely necessary, please make a comment first, and then we can both discuss changing them.

**Resources:**
- ecdsa package: https://golang.org/pkg/crypto/ecdsa/

**Comment by jldistefano** [comment]
Completed
