### ISSUE TITLE
Second project restructuring

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#151]
After doing some more digging on go project structure standards, I found what appears to be a newer consensus (sing 1.11) on what is appropriate in the community. This issue is dedicated towards making a branch based off of `dev` and then restructuring the project using the directory layout suggested in the resource links provided. 

Resources:
https://vsupalov.com/go-folder-structure/
https://github.com/golang-standards/project-layout

**Comment by jldistefano** [comment]
Completed
