### ISSUE TITLE
MakeContract support for minting (aka inflation) contracts

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#155]
branch: `angle2.0`

I commented out all the test cases and functions except for everything relevant to `MakeContract`. Add an additional check inside of `MakeContract` that checks if the sender private key passed in is nil. If it is, set the `Contract` `sender` field to be nil.

What is an inflation contract? The aurum supply will grow at a fixed rate, and the way this is done is through "null-sender" contracts. This means that there is no sender; the aurum just appears and is deposited in the recipient's account.

**Comment by HarryL5004** [comment]
Should I make a pull request to `Angle` if the unit test passes?

**Comment by kstola2** [comment]
Make a PR to dev

**Comment by HarryL5004** [comment]
Completed
