### ISSUE TITLE
Serialize contract to support null-sender contracts

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#157]
branch: `angle 2.0`

Now that we can make null-sender contracts, we need to update the `Serialize` function. Test has been update on the `angle 2.0` branch.

**Comment by HarryL5004** [comment]
When the contract's sender pubkey is nil, should we serialize it by making a byte slice with 178 zeros?

**Comment by kstola2** [comment]
@HarryL5004 Yeah, it should basically be an equal length byte string of all zeros (I'm hoping my test for that works, if it doesn't let me know).

Side note: we will need to check for this in the validation function later.

**Comment by HarryL5004** [comment]
This is what the byte slice looks like in the unit test for this statement `bytes.Repeat([]byte(strconv.Itoa(0))`:
![image](https://user-images.githubusercontent.com/42977312/56993965-69a70a80-6b63-11e9-8ebc-ebe22c10b283.png)
Is this an expected result?

**Comment by kstola2** [comment]
No it should be all zeros, unfortunately my pc died but if you build figure out how to change it to be 178 zeros other than just manually putting in 178 zeros then go for it. Otherwise do the brute force way.

**Comment by HarryL5004** [comment]
These two lines are giving me an error:
![image](https://user-images.githubusercontent.com/42977312/56995592-d15f5480-6b67-11e9-9242-96b9d5fc523f.png)
![image](https://user-images.githubusercontent.com/42977312/56995608-d9b78f80-6b67-11e9-8579-b0f7e40e7c00.png)
![image](https://user-images.githubusercontent.com/42977312/56995639-ecca5f80-6b67-11e9-9d57-6e7ea4ac406d.png)
Should I change `%s` to `%v`?

**Comment by kstola2** [comment]
Yeah that works

**Comment by HarryL5004** [comment]
Completed
