### ISSUE TITLE
Deserialize contract support for null sender

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#159]
Following up on #157 with deserialize, same branch as that issue.

**Comment by HarryL5004** [comment]
I don't quite understand why the unit test is failing even though the pointers seem to be the same:
![image](https://user-images.githubusercontent.com/42977312/57004423-890a5b80-6b94-11e9-9efa-38c2191fbcda.png)
![image](https://user-images.githubusercontent.com/42977312/57004436-9b849500-6b94-11e9-8e7c-ea35d6ad0483.png)

**Comment by kstola2** [comment]
@HarryL5004  Ah, I should've probably used `reflect.DeepEqual` instead of `!=`. Try that.

**Comment by HarryL5004** [comment]
Completed
