### ISSUE TITLE
Insert new account into table 

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#161]
branch : `angle2.0`

I'm planning on splitting up the update account table function into 3 functions:

- inserting a brand new account with some value into the table
- updating an existing account with minted aurum
- updating two accounts who have made some sort of exchange of value

This issue deals with the first case. The test case for it is simple. Use the existing `UpdateAccount...` code to complete it and return `errors` with custom explicit messages.

**Comment by HarryL5004** [comment]
Completed
