### ISSUE TITLE
Remaining Update table functions

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#165]
branch: `angle2.1`

`dev` has been restructured once again and with that comes a new `angle` branch. So we have `angle2.1`. 

The remaining two update-table functions, one that deals with two accounts being updated simultaneously and one that has to do with minting, now have tests associated with them. Write the code to pass them. They should be similar to the previous update-table function, just follow the function stub description.

**Comment by HarryL5004** [comment]
I think the arguments for the test is missing the `dbConnection` in `TestExchangeBetweenAccountsUpdateAccountBalanceTable`. It is giving me a nil pointer error when I try to create a row to query.
![image](https://user-images.githubusercontent.com/42977312/57115023-f394d600-6d11-11e9-8678-e78c3f3f0ae6.png)
![image](https://user-images.githubusercontent.com/42977312/57115161-d0b6f180-6d12-11e9-97be-38860f1330c5.png)

**Comment by kstola2** [comment]
@HarryL5004 You're right, I pushed the change to the branch. Sorry about that.

**Comment by HarryL5004** [comment]
Completed
