### ISSUE TITLE
producer main.go CPU usage investigation

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#166]
I noticed that running the `producer main.go` file causes a lot of CPU usage. Me and @Vineet77 noticed this must be due to the busy loop we currently have. I noticed that moving the `WorkLoop` code into the main body instead of actually calling it as a function causes a significant increase in efficiency, though the CPU usage is still high. Any other optimatization suggestions should be evaluated, including giving the busy loop something to do. The reason the loop is a simple busy loop right now is because we haven't assigned it something to do in the case that it isn't receiving any connections. Eventually it will be checking time elapsed, determining whether it's time to add a new block or not.

**Comment by bashbashbash** [comment]
I have made the changes and run main - on my machine (OS X), 100% CPU usage. Pushed the changes to bash branch

**Comment by kstola2** [comment]
So I think a good approach could be to make two threads, one thread for accepting/handling connections, and another for setting an alarm that runs in a loop and creates a block after x seconds ([example](https://stackoverflow.com/questions/35009070/alarm-like-timer-functionality-in-golang)).

The main thread would join on the two go routines, using a [waitgroup](https://golang.org/pkg/sync/#WaitGroup).

**Comment by kstola2** [comment]
So I removed the `default` case on the `select` statement... and it solved the problem lmao. Will commit changes in the future.

I guess `select` does not need a default case, and blocks on until a branch is available.

**Comment by bashbashbash** [comment]
Confirming issue has been resolved?

**Comment by kstola2** [comment]
Yes

**Comment by kstola2** [comment]
Resolved.
