### ISSUE TITLE
Let's make our first block

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#171]
branch: `first-block`

package context: `producer`

The goal of this issue is to start putting everything together and build the first block of our blockchain. Below I have supplied a structure of an Aurum Block. 

## What is the genesis block?

The genesis block is the **very first**, and forever oldest block in the blockchain. In Aurum, this block has a null previous hash, because it is the progenitor of the blockchain. Every subsequent block will chain hashes that can be traced all the way down to this block. This will make two blockchains only identical if the blocks starting from the genesis block all the way to the top match. 

## What is an airdrop?

The genesis block holds a collection of intial Aurum supply contracts. This means that, for `n` supplied key hashes, `n` null-sender contracts are created. The value of each of these contracts is calculated from: 

`initial Aurum supply / n`

Airdropping should create a blockchain file and metadata table based on the names supplied and call `AddBlock` with the genesis block.

NOTE: The `MakeContract` function now takes in the `currentNonce` of the sender, and adds 1 to it in the resulting contract. This means making a contract with a parameter of zero will result in a contract with a nonce of 1. For the purposes of the airdrop, you will need to manually set the `StateNonce` to 0 after `MakeContract` is called. This is done in the tests so check that out for reference.

EDIT: I'm going to change it to have `MakeContract` use a `nextStateNonce` parameter instead of automatically increment it... **Disregard note above**

![image](https://user-images.githubusercontent.com/31855040/57274789-f66d2f00-7061-11e9-8c8e-84cf8298eb63.png)

**Comment by HarryL5004** [comment]
In the unit test for `Deserialize`, is it intended for the test to use `Data`'s `Deserialize` func to deserialize a serialized `Contract`? Or should it be deserializing a serialized `Data`?

`136:	initialContract, _ := accounts.MakeContract(1, nil, spkh, 1000, 0)`
`144:	serializedInitialContract, _ := initialContract.Serialize()`
`157:				serializedData: serializedInitialContract,`
`163:			if err := tt.d.Deserialize(tt.args.serializedData); (err != nil) != tt.wantErr {`

**Comment by kstola2** [comment]
I see what you mean. It should be deserializing the Data. I've pushed the fix to the branch.

**Comment by HarryL5004** [comment]
I'm not so sure why I'm getting a nil pointer reference when I try to access `d`'s data members (such as `d.Hdr.Version`) in `Deserialize`.

**Comment by kstola2** [comment]
@HarryL5004 `d` is passed in as a `(*Data)(nil)`, so it's a `nil` pointer cast to a `Data` pointer.

**Comment by HarryL5004** [comment]
`tt.d` in `Deserialize` is `nil` no matter how I assign `d` to a new `*Data` in `Deserialize(...)`. However, the code for `Deserialize(...)` works if `tt.d` is instead initialized as a pointer to a default-valued `Data` (`d: &Data{}`)...

**Comment by kstola2** [comment]
@HarryL5004 

https://play.golang.org/p/FeXoeIgOgdr

Try this, see if it helps?

**Comment by HarryL5004** [comment]
I've tried that approach before, it did not work

**Comment by kstola2** [comment]
Is it giving you a nil pointer deference when you try that approach?

**Comment by HarryL5004** [comment]
No, the test just tells me that "deserialized data struct failed to match". When I print `tt.d` out, it's just `nil`.

**Comment by kstola2** [comment]
Hmmm okay. Change the test to use a default valued struct then.

**Comment by HarryL5004** [comment]
In the test for the genesis block, I think the value for each of the test contracts should be 10 instead of 1000, since the initial Aurum supply is 1000 and there are a hundred key hashes created.

`242:	for i := 0; i < 100; i++ { // One Hundred null-sender test contracts`
`246:		someAirdropContract, _ := accounts.MakeContract(1, nil, someKeyPKHash, 1000, 0)`
`271:				initialAurumSupply:     1000,`

**Comment by kstola2** [comment]
Im not near a computer right now but if there's an arithmetic discrepancy then feel free to change it so long as the above formula holds

**Comment by HarryL5004** [comment]
In the air drop test, I think `fileGenny` will always be different from `serializedGenny`, since `AddBlock(...)` also adds the length of the serialized block in front of the serialized block in the blockchain file.

`339:			serializedGenny := genny.Serialize()`
`340:			if !bytes.Equal(fileGenny, serializedGenny) {`

**Comment by kstola2** [comment]
You have a point. For the purposes of the test, you can either append the size to serializedGenny or index fileGenny[(index where block starts):(end of block)

**Comment by HarryL5004** [comment]
Do you want to remove `blockchain.dat` and `metadata.tab` at the end of the air drop test as well?
Also, I am having trouble with the block's `timestamp` again when I run the tests for `genesis` and `createBlock`... If I don't comment the `timestamp` out, the tests would fail arbitrarily. I'm not sure how to resolve this problem.

**Comment by kstola2** [comment]
Don't remove them at the end of the airdrop function, but they should be being removed at the end of the airdrop test, are they not? As far as the timestamp thing, if the blocks are being compared, just do `reflect.DeepEqual` on all the fields except for the timestamp.

**Comment by HarryL5004** [comment]
The airdrop test currently does not remove those files at the end of the test. Should I add the `defer os.remove` statements into the test?

**Comment by kstola2** [comment]
Yeah the same block that similar tests use

**Comment by HarryL5004** [comment]
Completed
