### ISSUE TITLE
Send Aurum function

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#172]
branch `client-send-contract`

package context: `client`

The purpose of this issue is to create the function that sends an aurum contract request to the producer. The producer in turn validates the contract and decides what to do with it.

The structure of a contract request introduces the "secret bytes" first. These are a collection of bytes that prepend the request; their purpose is to mark the message as something Aurum related. If the producer gets a message without these bytes, it discards it immediately. 

After that, the version of the data header as well as the type of payload that follows is appended to the request.

Use the wallet that is set up called `aurum_wallet.json` to retrieve the private key and nonce necessary to make the contract.

**Comment by bashbashbash** [comment]
Checking that the target file is in cmd and are there any tests associated with this issue?

**Comment by kstola2** [comment]
There's tests on the branch mentioned

**Comment by kstola2** [comment]
also, the package is in internal I believe

**Comment by kstola2** [comment]
will revisit after issue #189
