### ISSUE TITLE
Get Account info feature

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#173]
branch: `query account balance table`

package context: `accounts`

The idea with this is to be able to respond to client account information queries. 

As an additional part of this issue, replace any code in the `accounts` package that this feature overlaps with.

**Comment by HarryL5004** [comment]
For the `AccountInfo_Deserialize` test, ``tt.accInfo`` will always be `nil` regardless of the changes occurred in the `account info deserialize` function.

`857: accInfo: (*AccountInfo)(nil),`
`866: if !reflect.DeepEqual(tt.accInfo, ac) {`

example: https://play.golang.org/p/aGZyFjrJlxA

**Comment by kstola2** [comment]
@HarryL5004 this was the same issue as before with using the cast `nil` pointer, I forgot that this issue had that same problem. I've corrected it and pushed to this branch, so it now should be fine.

**Comment by HarryL5004** [comment]
Completed
