### ISSUE TITLE
RecoverMetadata support for Account balance Table

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#176]
branch: `metadata with accounts`

package context: `internal producer`

Firstly, I've moved the `blockchain.RecoverMetadata` function out of the `blockchain` package and into the `producer` package in order to circumvent a circular package dependency issue when modifying the corresponding test. We might as a group consider moving all the `blockchain` package into the `producer` package, since it seems these libraries overlap in purpose.

Now that we can create our genesis block, we need to make sure that upon genesis, both our metadata table and accounts table both are updated appropriately to support further block production and transaction validation. 

The new test for `RecoverMetadata` can be found in the `producer` package, and for now it simply tests making sure that both the metadata table and account balance table are properly initialized with the genesis block and the key hashes within it. A step 2 will be to implement a for loop with many blocks generated, making sure that if `RecoverMetadata` gets called at any point it will have the correct information.

**Comment by HarryL5004** [comment]
Completed
