### ISSUE TITLE
Memory statistics on main loop

### ISSUE THREAD

**Issue by Vineet77** [SIGBlockchain/project_aurum#186]
Working branch: _memory-stats_
Working files: _main.go_ in cmd/producer/main

So there is a concern the size of memory being used by our producer loop. The way go works is that if you declare a variable sized slice, it is automatically allocated on the heap. So when we generate a block every iteration in the loop, a new slice is allocated on the heap every iteration. 

Now we can safely assume that at one point the garbage collector will collect the slices (which are not longer being used), freeing memory. But it takes time for the garbage collector to sweep. This means that over time the total memory usage goes up as memory is be allocated faster than being freed. 

Ideally we want the total memory being used to be constant over the long run. The biggest influcencing factor is the time for block generation. The shorter the time period, the more memory allocated per second, which means that the garbage collector may fall behind. 

First add in random values in the block to add more memory to the block. Next collect the memory statisitcs as loop iterates over time. The 2 values we are concerned about are _count of heap object allocated_ and _count of heap objects freed_. The different between these two values should indicate the number of objects currently on the heap. We would like that number to be constant over time. 

Run the loop using different time interval values (range of 100ms to 10,000ms) and record the two values in a text file (also record the difference between the two values) and create a python script to create a graph of number of object currently on heap vs number of iterations. 

If you have any questions, comment down below.

**Comment by kstola2** [comment]
Make sure to run the `TestProducerGenesisFlag` test prior to running the loop, as it will not work otherwise.

To run the loop indefinitely, do `go run main.go -t -d --interval=[x]ms`
To make a block one at a time, run `go run main.go -d --interval=[x]ms`

**Comment by kstola2** [comment]
Resources:

https://dave.cheney.net/2014/07/11/visualising-the-go-garbage-collector
https://methane.github.io/2015/02/reduce-allocation-in-go-code/
https://dougrichardson.org/2016/01/23/go-memory-allocations.html
https://segment.com/blog/allocation-efficiency-in-high-performance-go-services/

**Comment by kstola2** [comment]
![image](https://user-images.githubusercontent.com/31855040/58295294-11df7600-7d94-11e9-96d0-9c69a387e70f.png)

This was done with the interval of 1 block/ second

**Comment by kstola2** [comment]
![image](https://user-images.githubusercontent.com/31855040/58444402-b2e46e80-80bd-11e9-9540-d4377054e987.png)
