### ISSUE TITLE
Setup Wallet additional case

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#198]
branch context: `new-client-main`

I've added an additional test case to the `client.SetupWallet` function in the internal client package. Basically, if the file `aurum_wallet.json` already exists, `SetupWallet` should return with an error stating that it already exists. This is to prevent overriding your private key by accidentally calling this function again. Just make the changes to the above branch context.

**Comment by HarryL5004** [comment]
completed
