### ISSUE TITLE
Aurum Logo

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#2]
Let's make a logo design for Aurum. Anyone with graphics design experience feel free to make something and we'll vote on it as a group.

**Details:** _Aurum_ means gold in Latin. So perhaps gold being the color would be interesting, although this is not a requirement (it can be any color). The logo can be simple; we're not looking for a coat of arms. However size is something to consider because it should be distinct enough to see it but small enough to fit in a native app window or the corner of a website. What's important is that it's original and not stolen from anywhere else. Honestly there aren't many restrictions on its appearance. Whatever you think is cool could be submitted and it'll be voted by everyone in the SIG.

**Comment by calvinmorett** [comment]
Could be helpful if you could provide some direction! Care to add a few keywords or similar projects/styles to guide it? ~Thank you.

**Comment by kstola2** [comment]
@calvinmorett sure I'll edit it to provide a little bit more detail.

**Comment by calvinmorett** [comment]
[https://imgeasy.com/images/Hw2o.png](rough ideas)  to get the ball rolling

**Comment by kstola2** [comment]
@calvinmorett These look great. We picked out a handful that we feel would work great. Can you possibly change up the colors on them?

**Comment by calvinmorett** [comment]
@kstola2 Yes, lets refine them and change the color styles up. Which ones are in consideration?

**Comment by kstola2** [comment]
IIRC these were the ones people liked:
![image](https://user-images.githubusercontent.com/31855040/52901128-7fdc3600-31c4-11e9-817f-59a5958b7ac2.png)

**Comment by calvinmorett** [comment]
[Style changes](https://imgeasy.com/images/Hdy4.jpg)

**Comment by kstola2** [comment]
@calvinmorett Can you make the logos gold with a black background?

**Comment by calvinmorett** [comment]
[Black Background](https://imgeasy.com/images/H8T5.jpg)

**Comment by kstola2** [comment]
@calvinmorett  Can we see what this looks like with the part cut off below the blue line?

![image](https://user-images.githubusercontent.com/31855040/53282745-df28d180-3701-11e9-8b72-8439f6908128.png)

**Comment by calvinmorett** [comment]
Excellent idea. Really cool how the logo has transformed.

![fjqJ.gif](https://imgeasy.com/images/fjqJ.gif)

**Comment by kstola2** [comment]
@calvin this looks really cool. Would you be able to do a gold to red gradient as a color?

**Comment by calvinmorett** [comment]
![image](https://user-images.githubusercontent.com/11654917/53290497-90675000-3772-11e9-9f4b-8ddd29b38871.png)

**Comment by bashbashbash** [comment]
I think it looks great!

**Comment by kstola2** [comment]
@calvinmorett I think we agree on using the last one.
