### ISSUE TITLE
Tests for Block comparison function

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#202]
package context: `internal/block`

We should implement custom equality functions for our structs, so let's start with block. Write a function stub in the above context called `Equals` that takes two `Block` structs as arguments and returns a `bool` determining whether they are equal or not. No need to output an error. Write the corresponding test.

A good test would involve one test case where the blocks are indeed equal, and then a test case for each field where all but one field are equal. Using a custom test-args struct for the test like in the generated go unit tests might be a good idea.

Some interesting resources for this:
https://stackoverflow.com/questions/18926303/iterate-through-the-fields-of-a-struct-in-go
https://golang.org/pkg/reflect/

Once this issue is completed, make an issue to fill out the function body.

**Comment by HarryL5004** [comment]
Should I create a PR to dev for this issue?

**Comment by kstola2** [comment]
Yes or you can just finish the function and then make the PR your choice

**Comment by HarryL5004** [comment]
Completed
