### ISSUE TITLE
Tests for Contract Comparison Function

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#203]
package context: `internal/producer/accounts`

Just as in issue #202 , we should have the same sort of `Equals` function for our `accounts.Contract` struct. This issue is to make the tests for it. Make sure to have multiple cases with one being a "true" comparison and the rest being "false" comparisons because of an individual field.

**Comment by bashbashbash** [comment]
Tests for Contract Comparison Function PR #209 - complete

**Comment by kstola2** [comment]
Completed
