### ISSUE TITLE
Splitting the ValidateContract function

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#204]
package context: `internal/producer/accounts`

Currently the `ValidateContract` function is a single point workhorse of for accounts table management. In the interest of better being able to communicate with clients and preventing premature table updating, I believe that it is best to split the `ValidateContract` function into two separate responsibilities:

1. `ValidateContract` should remain the method that simply outputs whether a contract is indeed valid, in the form of a `bool`.
2. A new function will handle updating the accounts table given a **valid** contract, by calling one of three functions that we `ValidateContract` currently calls  **(this will be a future issue)**

Make your own branch for this and make a PR for that. For now, comment out the current `ValidateContract` function and test, cut and paste them at the bottom of their corresponding files for reference. This should be a simple case of refactoring that code to support a simpler validation method with its corresponding test.

**Comment by HarryL5004** [comment]
Completed
