### ISSUE TITLE
Contract Message from Input feature

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#205]
package context: `cmd/client/main`
branch context: `client-main-new`

I made a function stub and test for a function `ContractMessageFromInput`. Basically it will take user input and output a serialized signed contract and prepended messaging protocol. The test is incomplete, so whoever takes on the issue can fill out the cases that I have prepared in the comments in the test function body.

**Comment by bashbashbash** [comment]
Tests for Contract Comparison Function PR #209 - complete

**Comment by HarryL5004** [comment]
Completed
