### ISSUE TITLE
New feature: GetMerkleRootHash

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#21]
**NOTE:** Requires Issue #20 to be completed.

**Workspace:**
- producer/src/block/block.go
- producer/src/block/block_test.go

**Objective:**
We need the Merkle root hashing function, which is a way to compress whatever data is being stored into a single hash. [Here's a useful link describing this process](https://hackernoon.com/merkle-trees-181cb4bc30b4)

**Testing:**
Test cases that must be passed:

1. Create a function called `GetMerkleRootHash`. This takes in a slice of byte slices and outputs the same. This function was already made in Project Allium but we need it here in Go. For reference, check out the  [Allium Python code](https://github.com/SIGBlockchain/project_allium/blob/master/src/data_structures/block.py), all the way at the bottom. Note that there are two functions to make this recursive: a calling function and a recursive function. Also note that in the Allium version, we do a single call of the hashing function, however we ought to layer our security more and do a double hash (hash the result of the hash function).

**Resources:**
- [Go SHA-256 Package](https://golang.org/pkg/crypto/sha256/)
- [Go Time Package](https://golang.org/pkg/time/)
- [Go Testing Package](https://golang.org/pkg/testing/)
- [Go Logging Package](https://golang.org/pkg/log/) (for detailed debug printing)

**Comment by Csando6** [comment]
Hello, I have been working on code for this part. I have been able to successfully create a recursive function that, if the length is of odd length - makes it event, and keeps on merging two elements until it returns a single root.

What I want to know is, how should I hash the elements. Should I....
>hash an element twice, merge, and hash again
>hash element a and b once, merge, and hash again
>hash element a and b once, merge and return

attached will be my code:
[appendHash.txt](https://github.com/SIGBlockchain/project_aurum/files/2898624/appendHash.txt)



 Thanks, 
Charly Sandoval

**Comment by kstola2** [comment]
@Csando can you make a pull request from your branch to dev? The instructions are located in `docs/` in Developer P & P

**Comment by Csando6** [comment]
@kstola2 , should I clone the project, edit, then pull from my branch to dev.

Also, not to sure what docs/ is referencing. Where can I find this?

**Comment by kstola2** [comment]
https://github.com/SIGBlockchain/project_aurum/tree/dev/docs

**Comment by kstola2** [comment]
@Csando6 

To answer your question about hashing, this is the python code we used to do this function for allium:

```
def get_merkle_root(hashed_tx_list):
    """
    Calls the recursive helper function if the length
    of the hashed tx list is greater than 0.
    :param hashed_tx_list: a collections.deque object
    containing SHA-256 hashed byte strings
    :return: a single SHA-256 hashed byte string 
    """
    if len(hashed_tx_list) < 1:
        return None
    else:
        return _get_merkle_root(hashed_tx_list)

def _get_merkle_root(merkle_list):
    """
    Recursive helper function that pairs up
    adjacent elements and hashes them, then repeats
    until a single hash is left.
    :param merkle_list: a collections.deque object
    containing SHA-256 hashed byte strings
    :return: base case is a single hash otherwise
    a deque containing an even length deque
    of hashed byte strings
    """
    if len(merkle_list) == 1:
        return merkle_list.pop()
    else:
        if len(merkle_list) % 2 != 0:
            merkle_list.append(merkle_list[-1])
        sz = len(merkle_list)
        for i in range(int(sz/2)):
            p1 = merkle_list.popleft()
            p2 = merkle_list.popleft()
            merkle_list.append(hash_SHA(p1 + p2))
return _get_merkle_root(merkle_list)
```

As you can see, we have two functions, a calling function and the recursive helper. (NOTE: In _Allium_ we only hashed things once but here we should do it a double hash). As for how to hash the input, you need to concatenate the two hashes first, then double hash them to get one, and repeat that process until you get a root hash. If you encounter a hash without a pair, duplicate that hash and concatenate it with itself (with the exception of the root hash of course). The use of a `deque` in Go makes this a lot easier.

**Comment by Vineet77** [comment]
Closing issue,
