### ISSUE TITLE
`ToString` function for `Block` struct

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#211]
Create a function in the `block` package that uses a `Block` struct as a receiver and returns a `string`. The string should be newline separated `Block` values. For any `byte` slices, `hex.Encode` them first.

A useful function for this would be https://golang.org/pkg/fmt/#Sprintf

Make sure that each value is separated by a newline.

**Comment by HarryL5004** [comment]
Completed
