### ISSUE TITLE
ToString function for Contract struct

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#212]
Create a function in the `accounts` package that uses a `Contract` struct as a receiver and returns a `string`. The string should be newline separated `Contract` values. For any `byte` slices, `hex.Encode` them first.

A useful function for this would be https://golang.org/pkg/fmt/#Sprintf

Make sure that each value is separated by a newline.

**Comment by bashbashbash** [comment]
Complete
