### ISSUE TITLE
Request Wallet info feature sends a message from the client to the producer to update wallet info

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#213]
Given a flag passed to the client main `-u`, I want to send a message to the producer that requests account info related to the supplied wallet address. Update `aurum_wallet.json` with the response.

**EDIT**:
While working on this issue, I accidentally bricked my motherboard and lost all unsaved changes, so now I need to try and reproduce the steps I took. Here they are:
Steps that need to be completed for this to work:
1. We need to move all _non-main_ functions and tests from the `cmd/producer/main` package into `internal/producer/src/producer` package.
- Note that this may cause errors associated with import cycles; the way I resolved this was looking for any variables/functions in the conflicting files that used the violating import and made sure that that function or variable is using a package definition. An example of this I remember is when moving the `RunServer` function, It typically used `producer.SecretBytes`. However when moving this variable to the `internal/producer/src/producer` package, it should be renamed to simply `SecretBytes`, since they are already in that package. This will require some surgical navigation but I will be available to help. 
- You should also copy the `genesis_hashes.txt` file into the destination package in order to make some tests pass, because if I recall correctly the `ReadGenesisHash` test function deletes this file. Simply make it not delete the file so that the other files will pass.
2. It appears that there are some discrepancies in the functions using the account balance table name among the different packages. In order to guarantee they are all using the same one, we need to change all of them to the same name. A method I chose 
3. After these two steps, run `go test` at the project root to make sure all the tests in Aurum are passing. If they aren't and the above two steps are completed, please let me know and we'll resolve it. IIRC all the tests should pass at this point.
4. I already wrote the function and function body for this issue. It is located [here](https://github.com/SIGBlockchain/project_aurum/blob/requestwalletinfo/internal/client/src/client/client.go) on lines 382-415. A simple copy paste should do.
5. Writing a test for this is going to be tough. Fortunately there already exists a test that mimics this behavior, and that's the response function for this particular request. The `TestResponseToAccountInfoRequest` test located in [dev here](https://github.com/SIGBlockchain/project_aurum/blob/dev/cmd/producer/main/main_test.go) is basically the response version of this request. In order to make this test be feasible, set up a wallet, insert it into a database as an existing account with custom values, then run `go RunServer` to spin up a server. Call the request function, which will receive a `thank you` message followed by the actual response. This response should be parsed to how the producer sends the message in the aforementioned test. Check to make sure it matches the custom values you previously inserted, and it's done.
6. Given the `-u` flag when running [client main](https://github.com/SIGBlockchain/project_aurum/blob/dev/cmd/client/main/main.go)  (observe the last `if` block) call the `Request...` function -> `UpdateWallet`, -> `PrintInfo`.

**Comment by kstola2** [comment]
Working on this, almost complete.

**Comment by HarryL5004** [comment]
I encountered an import cycle error from running `go test` at the project root after copying and pasting the `RequestWalletInfo` func into `client.go`.

**Comment by kstola2** [comment]
@HarryL5004 were you able to resolve this problem?

**Comment by HarryL5004** [comment]
Yup, I resolved it by copying and pasting `SecretBytes` from producer into `RequestWalletinfo`.

**Comment by kstola2** [comment]
What is the import error saying? You shouldn't have to actually put the secret bytes in the function. The idea is to use it as a global.

**Comment by HarryL5004** [comment]
![image](https://user-images.githubusercontent.com/42977312/59648987-8664c500-9146-11e9-9e49-88717549a703.png)
The import error occurred is because `client.go` imported `producer` pkg for `SecretBytes`, and `producer_test.go` imported `client` pkg for `GetWalletAddress` and `SetupWallet`.

**Comment by kstola2** [comment]
can you make a global `var` in `client.go` that is `SecretBytes` instead of putting it in the function? Does that work?

**Comment by HarryL5004** [comment]
Yeah, that works.

**Comment by HarryL5004** [comment]
I've written a simple test for `RequestWalletInfo`. Should I push the changes I've made so far to `requestwalletInfo2`?

**Comment by kstola2** [comment]
That's not necessary we can just use whatever branch you're working on.

**Comment by kstola2** [comment]
@HarryL5004 if the testing is getting a bit rough, we can discuss on discord how to maybe break apart the function into something a little more clean.

**Comment by HarryL5004** [comment]
The test for the `RequestWalletInfo` works on my machine, but I am getting an error for `TestResponseToAccountInfoReq..` saying "No connection could be made because the target machine actively refused it.".

**Comment by kstola2** [comment]
Make sure both functions are listening on different ports.

**Comment by HarryL5004** [comment]
`TestResponseToAccountInfoReq..` is still returning the same error after changing ports.

**Comment by kstola2** [comment]
Can you make a PR so I can get eyes on the code

**Comment by HarryL5004** [comment]
What should the producer address be for `RequestWalletInfo` in `client main` given the `-u` flag?

**Comment by kstola2** [comment]
it will be whatever gets passed in as the address, it should look like the second parameter you pass into `net.Dial()`

**Comment by HarryL5004** [comment]
Completed
