### ISSUE TITLE
Fracture block package

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#224]
Separate the functions, structs, tests within the `block` package into the following packages:

`block`:
- `Block`
- `BlockHeader`
- `CreateBlock` (from `internal/producer/src/producer`; should rename to `New`)
- `GetHeader`
- `Serialize`
- `Deserialize`

` hashing`:
- `HashSHA256`
- `GetMerkleRootHash`
- `getMerkleRoot`
- `HashBlock`
- `HashBlockHeader`

This may cause some tests to fail because of renaming and import problems, so make sure to run `go test` at root to see which ones need to be refactored.

**Comment by kstola2** [comment]
EDIT: @HarryL5004 Can you create a struct for `hashing` called `SHA256Hash`, and change the function name `HashSHA256` to `New`?

**Comment by HarryL5004** [comment]
I think it is better to leave `HashBlock` and `HashBlockHeader` in the block package. There was an import cycle error when both of those functions are placed inside the `hashing` package, and fixing the error requires more than just copying a few structs/variables.

**Comment by HarryL5004** [comment]
Completed
