### ISSUE TITLE
Add error returns to keys functions.

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#228]
Currently the encoding & decoding functions in the `keys` package are simply ignoring errors within the function body instead of returning them if they are faulty. If a conversion fails we should know about it and handle it gracefully instead of panicking.

This may cause some tests in the project overall to fail because of their current usage.

Example of area where an error needs to be handled: https://github.com/SIGBlockchain/project_aurum/blob/dev/internal/publickey/publickey.go#L23

- [x] all `privatekey` and `publickey` package functions handle errors if possible
- [x] all `privatekey` and `publickey` package tests pass
- [x] all usages of modified `privatekey` and `publickey` functions in repo refactored to handle errors
- [x] Use commit history to identify and validate changes

**Comment by bashbashbash** [comment]
via #306, this issue was resolved

**Comment by ramirez915** [comment]
Changes on the WIP regarding `publickey.Encode()` and `publickey.Decode()` for error handling look good to me and the changes throughout the project to account for these changes make sense to me.

**Comment by ramirez915** [comment]
In `privatekey.GenerateNRandomKeys()` on line 80, the line currently is `x509Encoded, _ := x509.MarshalECPrivateKey(p)` but the function `x509.MarshalECPrivateKey()` returns an error that is not handled. I think this should be changed to handle the error it returns but I'm not entirely sure. Aside from this, all tests pass.

**Comment by kstola2** [comment]
@ramirez915 Do we use that function anywhere? The `GenerateNRandomKeys`

**Comment by ramirez915** [comment]
I pulled from dev to check and did not find the `GenerateNRandomKeys` used anywhere in the project besides in privatekey_test.go file

**Comment by ramirez915** [comment]
I created a card regarding `GenerateNRandomKeys` in the backlog. Since `GenerateNRandomKeys` is not currently used anywhere in the project besides in privatekey_test.go the handling for the `x509.MarshalECPrivateKey()` can be ignored for now.
