### ISSUE TITLE
Fracture keys package

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#230]
`publickey`
- New struct: `AurumPublicKey { Key ecdsa.PublicKey } `
- `EncodePublicKey` -> rename -> `Encode`
- `DecodePublicKey` -> rename -> `Decode`

`privatekey`
- New struct: `AurumPrivateKey { Key *ecdsa.PrivateKey }` 
- `EncodePrivateKey` -> rename -> `Encode`
- `DecodePrivateKey` -> rename -> `Decode`

**Comment by HarryL5004** [comment]
Completed
