### ISSUE TITLE
Fracture accounts package

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#231]
`contracts`:
- `MakeContract` (should rename to `New`)
- `Serialize`
- `Deserialize`
- `SignContract` -> rename ->`Sign`

`accountstable`:
- `InsertAccountIntoAccountBalanceTable`
- `ExchangeBetweenAccountsUpdateAccountBalanceTable`
- `MintAurumUpdateAccountBalanceTable` (should consolidate to one update function)
- `GetBalance`
- `GetStateNonce`
- `GetAccountInfo`

`validation`:
- `ValidateContract`

`accountinfo`
- `AccountInfo`
- `NewAccountInfo` (should rename to `New`)
- `Serialize`
- `Deserialize`

**Comment by HarryL5004** [comment]
Completed
