### ISSUE TITLE
Full setup instructions for Mac OS developers in SIGBC

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#235]
Should include:
- installing Go
- installing Git
- cloning repository into GOPATH
- go get packages (sqlite3, getopt, etc.)

Wiki page: https://github.com/SIGBlockchain/project_aurum/wiki/Dev-Setup-Guide-(Mac-OS)

Example to go off of: https://github.com/SIGBlockchain/project_aurum/wiki/Dev-Setup-Guide-(Windows)

- [x] Install Go
- [x] Install Git
- [x] Install VSCode
- [x] Get project aurum repo

**Comment by bashbashbash** [comment]
Issue is complete pending review

**Comment by kstola2** [comment]
Completed
