### ISSUE TITLE
Make ExchangeBetweenAccountsUpdateAccountBalanceTable function take in a contract as a parameter

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#246]
This may make some tests fail, so refactor them after making the change.

Function this pertains to: https://github.com/SIGBlockchain/project_aurum/blob/dev/internal/producer/src/accountstable/accountstable.go#L43

Instead of having all those parameters, just pass in a contract and extract all of the needed information from it.

- [x] Change name to something shorter
- [x] Only connection and contract in parameters
- [x] All tests pass
- [x] All usages of modified function refactored

**Comment by kstola2** [comment]
Should we change the name of it?

**Comment by HarryL5004** [comment]
Completed
