### ISSUE TITLE
Change blockchain package I/O function file parameter

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#249]
Change I/O related functions to use file pointers/database connections instead of opening and closing excessively in the `blockchain` package.

https://www.vividcortex.com/blog/2015/09/22/common-pitfalls-go/

Example: [This](https://github.com/SIGBlockchain/project_aurum/blob/dev/internal/producer/src/blockchain/blockchain.go#L20) should be replaced with a database connection and a file pointer.

- [x] All blockchain package functions use file pointers or database connections
- [x] All blockchain package tests pass
- [x] All usages of modified blockchain functions in repository refactored

**Comment by HarryL5004** [comment]
Completed
