### ISSUE TITLE
New Feature: Client GetUserInput Function

### ISSUE THREAD

**Issue by bashbashbash** [SIGBlockchain/project_aurum#25]
**Workspace:**
- client/src/client/client.go
- client/src/client/client_test.go
- client/src/main/main.go

**Objective**:
We’ll need a way to get input from our user. To keep things simple, we will create a function to handle receiving user input as a string, which is returned after collection.

**Directive**
*Task 1:*
Write a function called getUserInput that return a string based on user input.
*Task 2:*
main.go should have an infinite loop that continuously calls this function, to get user input.
main.go should have an interface similar to the command line or gdb or similar interfaces, with a new line expecting input. ie)
`[aurum_client] | _`.
On input `q` it should exit the loop, possibly with a goodbye message.

**Testing:**
1. Create a test with that compares a string of your choice to the returned string from getUserInput. You’ll want to utilize the exec function from os, as well as StdoutPipe/StdinPipe.
2. Run main.go in project_allium/src/main, ensure that it quits on q.

**Resources:**
- [Go os Package](https://golang.org/pkg/os/)
- [Go bufio Package](https://golang.org/pkg/bufio/)
- [Go os/exec Package](https://golang.org/pkg/os/exec/)
- [Go io Package](https://golang.org/pkg/io/)
- [Go Testing Package](https://golang.org/pkg/testing/)
- [Go Logging Package](https://golang.org/pkg/log/) (for detailed debug printing)

**Comment by jldistefano** [comment]
completed
