### ISSUE TITLE
Change accounts package I/O function file parameter

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#250]
Change I/O related functions to use file pointers/database connections instead of opening and closing excessively in the `accounts` package

https://www.vividcortex.com/blog/2015/09/22/common-pitfalls-go/

Example: [This](https://github.com/SIGBlockchain/project_aurum/blob/dev/internal/producer/src/accountstable/accountstable.go#L110) should instead be a parameter that is passed in

- [x] All `accountstable` package functions use database connections passed in
- [x] All `accountstable` tests pass
- [x] All usages of modified `accountstable` functions refactored

**Comment by HarryL5004** [comment]
Completed
