### ISSUE TITLE
Block & Contract Equals functions with receivers

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#259]
Change `block` and `contract` `Equals` functions to use receivers instead of two parameters.

Example of how `publickey.go` does this: https://github.com/SIGBlockchain/project_aurum/blob/dev/internal/publickey/publickey.go#L28

- [x] `Block` Equals function uses receiver
- [x] `Contract` Equals function uses receiver
- [x] Tests pass

**Comment by HarryL5004** [comment]
Completed
