### ISSUE TITLE
New Feature: GetKeys

### ISSUE THREAD

**Issue by bashbashbash** [SIGBlockchain/project_aurum#26]
**Workspace:**
- producer/src/keys/key.go
- producer/src/keys/key_test.go
- producer/src/keys/.keys.dat.json
- client/src/keys/key.go
- client/src/keys/key_test.go
- client/src/keys/.keys.dat.json

**Objective**:
We need a way to grab `private` and `public` keys for a given user. The `public` key is for verifying and signing the data. The `private` key is for secure access to associated data. The file that will be referenced is *.keys.dat.json*.

**Directive**
Task 1: Create the file `key.go` and `key_test.go`. There will be no testing
Task 2: The function should be called `getKeys`. You will need to open a file as a json object and parse it into appropriate fields. The field parameters should be `private` and `public` and the values will be the keys associated, which will be _hex strings_, see *[big.Int.SetString](https://golang.org/pkg/math/big/#Int.SetString)*. Return the strings separately in the parsed order. If the file does not exist, you will need to *fatal exit*.

```
{
  private : <value>,
  public: <value>
}
```

**Testing:**
1. Create .keys.dat.json if it does not exist
2. Open .keys.dat.json and check for same values returned by getKeys()
3. Assert( .keys.dat.json.public == getKeys().public )
4. Assert( .keys.dat.json.private == getKeys().private )

**Resources:**
- [Go Sprintf](https://golang.org/pkg/fmt/#Sprintf)
- [Go ecdsa](https://golang.org/pkg/crypto/ecdsa/)
- [Go Testing Package](https://golang.org/pkg/testing/)
- [Go JSON Package]( https://golang.org/pkg/encoding/json/ )
- [Go IO]( https://golang.org/pkg/io/ )

**Comment by jldistefano** [comment]
Completed
