### ISSUE TITLE
Fracture producer package

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#265]
Split up the `producer` package into the following packages:

`producer`
- `RunServer`
- `ProduceBlocks`
- `printMemStats`
- `calculateInterval`
- `triggerInterval`

`genesis`
- `BringOnTheGenesis`
- `Airdrop`
- `ReadGenesisHashes`
- `GenerateGenesisHashFile`

`privatekey`
- `GenerateNRandomKeys`

`blockchain`
- `RecoverBlockchainMetadata`
- `emptyFile`
- `extractBlock`
- `insertMetadata`

`accountstable`
- `updateAccountTable` (Might need to capitalize the "u" to make it publicly accessible)

Any functions that didn't make the list can be discarded (along with their tests)

These should be separate packages in `internal/`

- [x] All producer functions split amongst above packages
- [x] Move all above packages to `internal`
- [x] Remove the `src` folder from `producer`
- [x]  Dockerfile moved to repository root
- [x] All tests passing

**Comment by ramirez915** [comment]
Completed
