### ISSUE TITLE
pending validation function

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#269]
See: #268 

context: `validation`

Make a validation function that does the following:

Given a contract, a pending balance, and a pending state nonce:

- reject if the contract's value is zero
- reject if the sender public key is nil or if hashing it matches the recipient
- reject if the signature is invalid
- reject if the pending balance is less than the contract value
- reject if the contract state nonce is not 1 greater than the pending state nonce
- if rejected, return an error
- if valid, return nil for the error, and the new pending balance and state nonce (3 values)
- the new pending balance is `pending balance - contract value`
- the new pending state nonce is `pending state nonce + 1`

**Comment by HarryL5004** [comment]
Completed
