### ISSUE TITLE
Fracture client package

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#272]
Fracture the client package into `internal/wallet`. This new package should contain:

- `SetupWallet`
- `GetPrivateKey`
- `GetBalance`
- `GetStateNonce`
- `GetWalletAddress`
- `RequestWalletInfo`
- `UpdateWallet`

Any functions/tests that don't make the cut should be removed along with the original `client` package.

The package should reside in `internal/`

- [x] New package `internal/wallet` created
- [x] Contains only functions mentioned above
- [x] Tests that support above functions are present in `wallet_test.go`
- [x] `client` root directory and all subdirectories deleted

**Comment by HarryL5004** [comment]
Completed
