### ISSUE TITLE
New Feature: GenKeys

### ISSUE THREAD

**Issue by LukieJoe** [SIGBlockchain/project_aurum#29]
**Workspace:**
- producer/src/keys/key.go
- producer/src/keys/key_test.go
- producer/src/keys/.keys.dat.json
- client/src/keys/key.go
- client/src/keys/key_test.go
- client/src/keys/.keys.dat.json

**Objective**:
We need a way to generate `private` and `public` keys for a given user. The `public` key is for verifying and signing the data. The `private` key is for secure access to associated data. The file that these will be stored in is *.keys.dat.json*.

**Directive**
Task 1: The function should be called `genKeys`. You will need to create a file called *.keys.dat.json*.
Task 2: Generate the `public` and `private` keys with [this](https://golang.org/pkg/crypto/ecdsa/). Test that the keys are correctly generated. 
Task 3: Create a JSON object with the below parameters. <value> is big.Int as provided by ecdsa.
Task 4: Convert big.Int into a hex_string (i.e. a series of hex characters) ( fmt.Sprintf("%X", key) )
Task 5: Dump the JSON into *.keys.dat.json*.

```
{
  private : <value>,
  public: <value>
}
```

**Testing:**
1. Create .keys.dat.json if it does not exist
2. Open .keys.dat.json
3. Assert( pre_conversion(keys) == post_conversion(keys) )
4. Assert( .keys.dat.json.public == getKeys().public )
5. Assert( .keys.dat.json.private == getKeys().private )

**Resources:**
- [Go fmt]( https://golang.org/pkg/fmt/#Sprintf )
- [Go ecdsa](https://golang.org/pkg/crypto/ecdsa/)
- [Go Testing Package](https://golang.org/pkg/testing/)
- [Go JSON Package]( https://golang.org/pkg/encoding/json/ )
- [Go IO]( https://golang.org/pkg/io/ )

**Comment by kstola2** [comment]
https://en.bitcoin.it/wiki/File:PubKeyToAddr.png

**Comment by jldistefano** [comment]
Completed
