### ISSUE TITLE
Make SQL statements Injection-Attack Proof

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#291]
In the `sqlstatements` package, make the statements injection-attack proof.

Example of how to do this: https://stackoverflow.com/questions/26345318/how-can-i-prevent-sql-injection-attacks-in-go-while-using-database-sql

- [x] Change `sqlstatements` per above
- [x] Refactor any code in the repository as necessary

**Comment by ramirez915** [comment]
Completed
