### ISSUE TITLE
Investigate masterTest script failing tests

### ISSUE THREAD

**Issue by bashbashbash** [SIGBlockchain/project_aurum#294]
Noticed when working in the dev branch of project_aurum, please see attached error log.[https://app.zenhub.com/files/168786377/3f16742f-f337-4112-a4e0-5bff6fe73752/download](https://app.zenhub.com/files/168786377/3f16742f-f337-4112-a4e0-5bff6fe73752/download)

**Comment by kstola2** [comment]
@bashbashbash has this been resolved? I just ran the script on @ramirez915 's branch and it worked fine.

**Comment by kstola2** [comment]
resolved
