### ISSUE TITLE
Style Guide and Format for code base

### ISSUE THREAD

**Issue by bashbashbash** [SIGBlockchain/project_aurum#298]
Based on refactoring, I am coming across various styles and formats that are somewhat unique to each contributor. I believe there are ways to autoformat code, and I suggest we agree upon a general format/style and implement this. This will increase readability and decrease time formatting. We when come up with a general format, we can document as well for reference/future updates.

**Comment by kstola2** [comment]
Great idea. Do you have any links on style guides or perhaps auto-formatting tools?

**Comment by bashbashbash** [comment]
Closing this issue because we do not want to move forward at this time with git hooks, which would require users to run an environment setup command (Makefile) in order for go fmt to run before committing to a branch
