### ISSUE TITLE
Contract history scanner

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#301]
Given a public key, scan the blockchain and return a list of metadata-objects describing every contract associated with that public key and its hash. The metadata-object should contain the wallet address of the sender and the recipient, value, and timestamp of the containing block.

- [ ] Custom metadata object created that contains 
- Timestamp of block that the contract is contained in
- Sender wallet address
- Recipient wallet address
- Value

Test setup with the following cases:
- [ ] Given a wallet address, a block with no contracts in it
- [ ] Given a wallet address, a block with that wallet address as the sender in a contract
- [ ] Given a wallet address, a block with that wallet address as a recipient in a contract

**Comment by bashbashbash** [comment]
This issue is now associated with creation of the ContractSummary Struct only, #417, and all other parts of the issue will be handled in other issues
