### ISSUE TITLE
TestRecoverBlockchainMetadata from blockchain_test failing

### ISSUE THREAD

**Issue by bashbashbash** [SIGBlockchain/project_aurum#308]
Read the attached error log below. It was discovered via issue #228 the a test in TestRecoverBlockchainMetadata from blockchain_test.go fails to handle a nil key case (the suspected cause, please confirm). Find the TODO comment in accountstable.go and fix the failing test.
[errors.txt](https://github.com/SIGBlockchain/project_aurum/files/3465772/errors.txt)

**Comment by HarryL5004** [comment]
Completed
