### ISSUE TITLE
Testing: jsonify

### ISSUE THREAD

**Issue by bashbashbash** [SIGBlockchain/project_aurum#318]
package context: internal/jsonify

Please create tests for the function LoadJSON. Please consider cases where interface is not empty, interface is invalid, interface is nil, file is nil, file is invalid, file is not open, and how to handle various errors returned. Also consider valid cases.

Please following file naming conventions for testing and please include comments to specify what each test is performing

**Resources:**
- [Go Testing Package](https://golang.org/pkg/testing/)
- [Go Logging Package](https://golang.org/pkg/log/) (for detailed debug printing)
- [Go reflect Package](https://golang.org/pkg/reflect/) (for comparison)

**Comment by harshalpatel165** [comment]
does a file being nil mean that that the file does not exist or that there is nothing within the file

**Comment by harshalpatel165** [comment]
tbh, I'm not sure what I'm supposed to be doing with this. Do I have to create an interface in the test and run the LoadJSON function with it. If so, what goes in the interface.

**Comment by harshalpatel165** [comment]
completed
