### ISSUE TITLE
Settings commands

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#321]
Currently `config.json` has the following structure:
```
{
    "Version": 1,
    "InitialAurumSupply": 50000000,
    "Port": "12000",
    "BlockProductionInterval": "20s",
    "Localhost": true
}
```

In an effort to make changes easier, create a separate `main.go` which will be a produce a binary that can change a particular configuration setting depending on what flag is specified.

So theoretically you would be able to run `someBinary -port 35000` and that would go into the `config.json` file and change the port.

Resource: https://golang.org/pkg/flag/

**Comment by HarryL5004** [comment]
Completed
