### ISSUE TITLE
Add posting to blockpub goroutine

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#332]
_Description_: BlockPub is a page owned by the ACM used by SIG Blockchain as a "meeting place" for active network users of Aurum. The idea here is to create a "heartbeat" for the producer, periodically advertising its IP:Port combo publicly to say its alive and accepting requests. 

- [ ] Call `nettools.GetIP` in `main.go` (right after the call to `http.ListenAndServe`
- [ ] Call `requests.AddPeerToDiscoveryRequest` and send it off
- [ ] Check http://blockchain.acmapp.tech/peers (under Raw Data) to see if the information is populated in the array (**Please screenshot this to show that it's working in your PR**)
- [ ] Make a goroutine that repeats `requests.AddPeerToDiscoveryRequest` send every 5 minutes

**Comment by Vineet77** [comment]
http://blockchain.acmapp.tech/peers is currently not working

**Comment by Vineet77** [comment]
Resolved by https://github.com/SIGBlockchain/project_aurum/pull/391
