### ISSUE TITLE
Response to brand new wallet address on update

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#333]
If a brand-new user of Aurum runs an update-info request and they are not in the table, they will currently receive a 404 error. This looks a bit alarming to new users who could be expecting a promised aurum transaction.

Focus point: https://github.com/SIGBlockchain/project_aurum/blob/master/internal/handlers/handlers.go#L50

- [x] Call `io.WriteString` with some text saying something to the effect of "if you're a new user, you may not be registered in the blockchain yet. You will not be registered until a block has been produced containing a transaction with you as the recipient. Please wait until the next block has been produced to check again"
- [x] Refactor test to account for this case
- [ ] BONUS: get the amount of time remaining until the next block and add it into the message.

**Comment by Vineet77** [comment]
The bonus is still not implemented, thus will keep issue open for now.

**Comment by kstola2** [comment]
@Vineet77 We can close this and make a separate low priority issue with just the bonus

**Comment by kstola2** [comment]
Completed
