### ISSUE TITLE
Block Validation

### ISSUE THREAD

**Issue by HarryL5004** [SIGBlockchain/project_aurum#344]
Package context: `internal/block`
Branch: `Block_Validation`

For this issue, add code to the `validate` function stub in `internal/block`. 
`Validate` should return **false** if:

- Block version does not match the version given in the parameter
- Block height does not match the height given in the parameter
- Block previous hash does not match the previous hash given in the parameter
- Block timestamp is before the timestamp given in the parameter
- Block timestamp is in the future

A test for this function is provided in the test file of package `block`.

Make sure to leverage the existing functions in `internal/hashing` and/or `internal/block`.

**Comment by kstola2** [comment]
@HarryL5004 wouldn't it make more sense to put this in the `validation/` package?
