### ISSUE TITLE
Endpoint for Handling Queries by Height and by Hash

### ISSUE THREAD

**Issue by bashbashbash** [SIGBlockchain/project_aurum#346]
**Workspace:**
- `internal/endpoints/endpoint.go`

Create a  constant in `endpoints.go` that will be used to accept incoming blocks by height. The endpoint should be `/block/height`

Create a constant in 'endpoint.go' that will be used to accept incoming blocks by hash. The endpoint should be `/block/hash`

**Comment by kstola2** [comment]
https://github.com/SIGBlockchain/project_aurum/blob/master/internal/endpoints/endpoints.go

**Comment by kstola2** [comment]
@bashbashbash What do you mean by "keys" here?

**Comment by bashbashbash** [comment]
> @bashbashbash What do you mean by "keys" here?

Good point - meant values and updated the issue statement

**Comment by harshalpatel165** [comment]
completed
