### ISSUE TITLE
Endpoint for incoming blocks

### ISSUE THREAD

**Issue by Vineet77** [SIGBlockchain/project_aurum#347]
Package context: `/internal/endpoints`

Create a  constant in `endpoints.go` that will be used to accept incoming blocks. The endpoint should be `/block`

**Comment by harshalpatel165** [comment]
does it matter what I name the constant, or do you need a specific name for the constant? Am I naming it based on what the constant does

**Comment by kstola2** [comment]
"/block" is fine

**Comment by harshalpatel165** [comment]
I mean the name of the constant

**Comment by harshalpatel165** [comment]
as like what goes before  ` = "/block" '

**Comment by kstola2** [comment]
Doesn't matter. pick what you want. Something short and succint.

**Comment by harshalpatel165** [comment]
completed
