### ISSUE TITLE
Wallet Address and Timestamp Table

### ISSUE THREAD

**Issue by HarryL5004** [SIGBlockchain/project_aurum#356]
Package context: `internal/wallet`
For this issue, make a new branch off of `dev` and create a function that initialize a table in package `wallet` with the following columns: 
- wallet address (text)
- timestamp for the last block produced by that wallet address (integer)

Please update `sqlstatements.go` with your sql statements and `constants.go` with the file name.

Helpful resources:
Package `sql`, https://www.w3schools.com/sql/sql_create_table.asp, `wallet.GetWalletAddress()`.

**Comment by kstola2** [comment]
Can you add labels and add the project tag

**Comment by HarryL5004** [comment]
Completed
