### ISSUE TITLE
Send Block Request

### ISSUE THREAD

**Issue by Vineet77** [SIGBlockchain/project_aurum#372]
Branch Context: `send_block`
Package context:  `requests`

Complete the function `SendBlockRequest` that given a block, creates a POST request to the incoming block endpoint with a JSON-block in the body. 

All unit tests must pass (look at `TestSendBlockRequest`)

**Comment by HarryL5004** [comment]
![image](https://user-images.githubusercontent.com/42977312/67165288-f4b1d200-f348-11e9-8fc4-00069ba05e8e.png)
I'm not sure why I am getting this error when these two `JSON Block` contain the same values.

**Comment by Vineet77** [comment]
My bad, I forgot a ! to the if statement. Can you push your changes to the branch and I'll modify the test

**Comment by HarryL5004** [comment]
I just pushed my changes to the branch

**Comment by Vineet77** [comment]
I fixed the test;.

**Comment by HarryL5004** [comment]
Completed
