### ISSUE TITLE
AAA Test: GetJSONBlockByHeight

### ISSUE THREAD

**Issue by bashbashbash** [SIGBlockchain/project_aurum#374]
Package context: `internal/handlers`
Branch: `getjsonblockbyheight`

Please create a AAA test in the above package using the listed branch. Using the height, you will leverage a query to the metadata table and extract the block at the given height, returned as a JSON-block.

Be sure to test for:
- [x] handling a height that exists in the chain
- [x] handling a height that does not exist in the chain

Useful links
[AAA Testing](https://github.com/SIGBlockchain/project_aurum/wiki/Unit-Tests)
[Blocks](https://github.com/SIGBlockchain/project_aurum/wiki/Blocks)
[Endpoint listening](https://github.com/SIGBlockchain/project_aurum/wiki/HTTP-Requests)

**Comment by Vineet77** [comment]
Unit test added

**Comment by Vineet77** [comment]
@bashbashbash Can you look at htis

**Comment by kstola2** [comment]
@Vineet77 Which branch?

**Comment by bashbashbash** [comment]
Looks like metatable.db and blockchain.dat are not removed in the test

**Comment by kstola2** [comment]
This would be a great opportunity for mocking

**Comment by bashbashbash** [comment]
Agreed - since this is part of squirtle sprint that is due today, perhaps we should complete it and then set up another issue to improve the test with mocking

**Comment by bashbashbash** [comment]
Looks good
