### ISSUE TITLE
New function for private key package

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#375]
- [x] Add `Bytes []byte` and `Hex string` fields to `AurumPrivateKey` struct
- [x] function called `New`, which creates an `AurumPrivateKey` struct
- [x] `Key` field is populated by generating a random private key (look [here ](https://github.com/SIGBlockchain/project_aurum/blob/master/internal/privatekey/privatekey.go#L75)for to see how this is done)
- [x] `Bytes` field set to the return of `privateKey.Encode` with the `Key` field as an argument
- [x] `Hex` field set to the return of `hex.EncodeToString` with `Bytes` field as argument
- [x] Test should just make sure that `Bytes` field is the encoded version of `Key` and `Hex` field is hex-encoded version of `Bytes` field

**Comment by HarryL5004** [comment]
Completed
