### ISSUE TITLE
New function for public key package

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#377]
- [ ] Create a struct called `AurumPublicKey` with `Key`, `Bytes`, `Hex`, `Hash`,  fields
- [ ] Create a function called `New` that takes in a `*ecdsa.PrivateKey` as a parameter and generates an `AurumPublicKey`
- [ ] `Key` fields should be set to the private key's public key like here: https://github.com/SIGBlockchain/project_aurum/blob/master/internal/publickey/publickey_test.go#L83
- [ ] `Bytes` field should be the return of calling `publicKey.Encode` with the `Key` as the parameter
- [ ] `Hex` should be set to the return of `hex.EncodeToString` with `Bytes` as the parameter
- [ ] `Hash` should be set to the return of `hashing.New` with `Bytes` field as a parameter
- [ ] Test should just check that each field is set according to above requirements

**Comment by Vineet77** [comment]
Resolved by https://github.com/SIGBlockchain/project_aurum/pull/390
