### ISSUE TITLE
DumpJSON

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#380]
The opposite of `LoadJSON`. Should take an interface parameter representing any Go struct, and an `io.Writer`. The body should marshall the first parameter and call Write with the second parameter. Here's a quick tutorial on how this works: https://medium.com/@as27/a-simple-beginners-tutorial-to-io-writer-in-golang-2a13bfefea02

Leverage the fact that we have two interface parameters to mock out the portion of the test that would normally create the file.

**Comment by bashbashbash** [comment]
Completed #385
