### ISSUE TITLE
MockIoWriter in mock package

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#386]
- [ ] Move `MockIoWriter` to `mock` package
- [ ] Implement `When` funcion
- [ ] Implement `Given` function 
- [ ] Implement `Return` function
- [ ] Implement `Check` function
- [ ] Test that supports generating `MockIoWriter`

**Comment by Vineet77** [comment]
Where is the MockIoWriter? I see a MockWriter in jsonify_writer.go

**Comment by kstola2** [comment]
> Where is the MockIoWriter? I see a MockWriter in jsonify_writer.go

Yeah, that's the one. You can rename it.

**Comment by Vineet77** [comment]
Putting a hold on this issue for now.
