### ISSUE TITLE
Unhandled error in GenerateNRandomKeys

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#398]
GenerateNRandomKeys() in privatekey.go uses a function called x509.MarshalECPrivateKey() on line 80 that is not being handled. If GenerateNRandomKeys() is ever used, make sure that the error returned by x509.MarshalECPrivateKey() is being handled.

contact @ramirez915 for details

**Comment by HarryL5004** [comment]
Completed
