### ISSUE TITLE
LedgerManager

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#412]
We should be able to mock out most the `blockchain` package functions in the future.

- [ ] Create an interface in `ifaces` called `ILedgerManager`. 
- [ ] This interface should contain the function signatures of every function in the `blockchain` package **if and only if they have both an `*os.File` and `*sql.DB` parameter. Omit these two parameters in the signature for the interface.**
- [ ] Also add a `Lock` and `Unlock` signature with no parameters and no returns
- [ ] Create a struct in the `blockchain` package called `LedgerManager`. It should contain a `sync.RWMutex`, a `os.File`, and a `sql.DB` field.
- [ ] Implement the methods. First, `Lock` and `Unlock` should call the same name function on the `sync.RWMutex` field.
- [ ] For the rest of the functions, simply call the corresponding `blockchain` package function. In the case of `AddBlock`, call `Lock` before calling that function and `Unlock` immediately after.

If you're not familiar with interfaces, locks, or db connections, there are resources listed in #410 . _Please read these first if you have any questions_.

**Comment by Vineet77** [comment]
What do you think about naming the struct to something like `dbLedgerManager`, indicating that the ledger manager uses a database.

**Comment by kstola2** [comment]
> 
> 
> What do you think about naming the struct to something like `dbLedgerManager`, indicating that the ledger manager uses a database.

It's technically using a db, but it's also using the `.dat` file. But both the sql connection and file pointer are used to manage the ledger as a system.

**Comment by kstola2** [comment]
Completed
