### ISSUE TITLE
List out all redundancies in client and producer repo

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#414]
I need a list of all the packages/functions that are found in both the `aurum_client` repo and `project_aurum` repo. I would just look in `aurum_client` and see if any of those functions are found in `project_aurum` since the former has less functions.

**Comment by arosso3** [comment]
Here you go:

`config.go`:
- `LoadConfiguration`

`contracts.go`:
- `Contract` struct
- `MakeContract` in `aurum_client`/`New` in `project_aurum`
- `Serialize`
- `SignContract` in `aurum_client`/`Sign` in `project_aurum`
- `Equals`

`hashing.go`:
- `HashSHA256` in `aurum_client`/`new` in `project_aurum`

`privatekey.go`:
- `EncodePrivateKey` in `aurum_client`/`Encode` in `project_aurum`
- `DecodePrivateKey` in `aurum_client`/`Decode` in `project_aurum`

`publickey.go`:
- `EncodePublicKey` in `aurum_client`/`Encode` in `project_aurum`
- `Decode`

`requests.go`:
- `NewAccountInfoRequest`
- `NewContractRequest`

`wallet.go`:
- `SetupWallet`
- `GetBalance`
- `GetStateNonce`
- `GetWalletAddress`
- `UpdateWallet`

**Comment by kstola2** [comment]
Thanks this will be valuable in an upcoming issue. You can close it if you're confident that's all there is
