### ISSUE TITLE
NewFromPublic

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#415]
I think it would be sensible to create a function called `NewFromPublic`, that does the same thing as `publickey.New` except it takes in an `ecdsa.PublicKey` as an argument. You can reuse the code that's in the already existing `New` function. You can also replace the existing code in `New` with a called to `NewFromPublic` after the call to `Public()`

**Comment by arosso3** [comment]
Which `new` function are you referring to?

**Comment by kstola2** [comment]
> 
> 
> Which `new` function are you referring to?

https://github.com/SIGBlockchain/project_aurum/blob/master/internal/publickey/publickey.go#L21

The idea is that you have two functions that produce an `AurumPublicKey` ; one that takes a `ecdsa.PrivateKey` (like the above linked function does) and another given an `ecdsa.PublicKey`, which is what this issue is.

**Comment by arosso3** [comment]
Should I need to write a new test for `NewFromPublic` or does the `new` test cover it since that function now calls  `NewFromPublic`?
