### ISSUE TITLE
IBlockchainStreamer

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#416]
Currently there is an interface called `IBlockFetcher`. This interface has a method that given a `uint64 height`, will fetch the particular block at that height. 

We will create a blockchain streamer, that will stream batches of blocks as well. 

The interface `IBlockchainStreamer` has a function called `Stream` which takes in a slice of `block.Block` and returns an `int` and an `error`. 

The next issue will be devoted to implementing this streamer.

**Comment by bashbashbash** [comment]
Complete #419
