### ISSUE TITLE
HashBlock, Deserialize, and Serialize fix

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#65]
**Expected Date of Completion:** 10-March-2019

**Workspace:**
- `producer/src/block/block.go`
- `producer/src/block/block_test.go`

**Objective:**
The following can all be done in sequential pull requests:

- First, a fix needs to be made: add an additional field to the block struct called `DataLen`, which is an _unsigned 16 bit integer_. This represents the length of or "number of items" in the `Data` field. The `Serialize` function and its corresponding test will need to be updated to reflect this change.

- Previous block hashes are made by hashing the header of a block. The block header is composed of every field **except** the `Data` and `DataLen` fields. Just pass in the concatenation of those fields similar to the way Serialize does it into the `HashSHA256` function. No test is required for this. The function stub for `HashBlock` is located in `block.go`.

- When we receive a block or extract a block, it will probably be useful to deserialize the `[]byte` to get more workable information. The function stub for `Deserialize` and its corresponding test (which should remain unaltered) are in the `block` package.

**Resources:**
- #10 , #20

**Comment by HarryL5004** [comment]
Hello, when I deserialize the byte slice of a block, can I assume that the 2d data byte slice in the new block to always contain only one big byte slice no matter how the 2d data byte slice was structured before serialization?

![untitled](https://user-images.githubusercontent.com/42977312/53910660-fe850000-4019-11e9-8c4d-4fcc530ff75e.png)

**Comment by kstola2** [comment]
@HarryL5004 That is a very good question. For now, yes you can consider it to be one big byte slice. Once we implement contracts we'll be able to separate those as well. For the test for this particular issue, our `Data` field is a slice of one element, which is the hash of 'r', which is a byte slice. Just write enough code to pass the test. 

It may be wise to do pull requests with one thing at a time here though, so if you have the `Serialize` fix and `HashBlock` done, lets get those out the way first so we can update the test for `Deserialize`.

**Comment by kstola2** [comment]
Follow up: I spoke to @Vineet77 , and it makes sense to prepend the size of each data element to the element itself when we serialize it. That way we have the number of elements in `DataLen` and we can deserialize each individual element.

**Comment by Vineet77** [comment]
@HarryL5004 I pushed a new version of serialize onto my branch (haven't tested it yet, need deserialize), so when you work on deserialize, you can use that as a reference. To test it out, either pull from my branch (vineet) or pull to to my branch and run a test. Feel free to message me if you have any questions.
