### ISSUE TITLE
New feature: Client Send

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#79]
**Expected Date of Completion:** 10-March-2019

**Workspace:**
- `client/src/client/client.go`
- `client/src/client/client_test.go`

**Objective:**
This function will handle sending a stream of bytes to the producer. It is the first issue in a series that begins to connect the producer and the client together.

**Testing:**
The max length of our messages will be 1024, so for messages longer than that a for loop will need to be implemented while sending a stream.

EDIT: The for loop is no longer necessary so long as we limit client messages to be less than 1KB.

**Resources:**
- [Go net package](https://golang.org/pkg/net/)

**Comment by jldistefano** [comment]
Completed
