### ISSUE TITLE
Yields for Contracts

### ISSUE THREAD

**Issue by kstola2** [SIGBlockchain/project_aurum#98]
**Expected Date of Completion:** 17-March-2019

**Workspace:**
- `producer/src/contract/contract.go`
- `producer/src/contract/contract_test.go`

**Objective:**
Review the way contracts work by reading through the [slides on them](https://github.com/SIGBlockchain/project_aurum/blob/dev/docs/Contracts.pdf).

In this issue we will start building out `Yields` and their corresponding `Unclaimed Yield Pool`. Yields basically denote who has access to a particular chunk of aurum. The UYP is a database table of yields that have yet to be consumed. When you build a contract, you will remove the yields being claimed (consumed) and insert the yields resulting from that transaction.

 The UYP has 4 fields:
- The height of the block that the contract which has the yield is stored in.
- The hash of the contract the yield is stored in
- The index of the yield in the array of yields in that contract
- The rightful holder of the aurum in that yield (ie. the only authorized claimant)
- The value of that yield

Big picture representation:
![image](https://user-images.githubusercontent.com/31855040/54223182-ece1a380-44c4-11e9-89da-19328ac2e20c.png)

**Testing:**
Tests are located in `contract_test.go`.

**Resources:**
- [Go ecdsa](https://golang.org/pkg/crypto/ecdsa/)
- [Contracts](https://github.com/SIGBlockchain/project_aurum/blob/dev/docs/Contracts.pdf)

**Comment by Vineet77** [comment]
I'll work on this, if anyone wants to come along, let me know!

**Comment by kstola2** [comment]
Completed.
